//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Author
{
    public Author()
    {
        this.Books = new HashSet<Book>();
    }

    public int AuthorKey { get; set; }
    public string AuthorName { get; set; }

    public virtual ICollection<Book> Books { get; set; }
}

public partial class Book
{
    public Book()
    {
        this.Reviews = new HashSet<Review>();
        this.Authors = new HashSet<Author>();
        this.Categories = new HashSet<Category>();
    }

    public int BookKey { get; set; }
    public string BookTitle { get; set; }
    public System.DateTime BookEntryDate { get; set; }
    public string BookISBN { get; set; }

    public virtual ICollection<Review> Reviews { get; set; }
    public virtual ICollection<Author> Authors { get; set; }
    public virtual ICollection<Category> Categories { get; set; }
}

public partial class Category
{
    public Category()
    {
        this.Books = new HashSet<Book>();
    }

    public int CategoryKey { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<Book> Books { get; set; }
}

public partial class Review
{
    public int ReviewKey { get; set; }
    public int BookKey { get; set; }
    public int ReviewerKey { get; set; }
    public System.DateTime ReviewDate { get; set; }
    public string ReviewTitle { get; set; }
    public int ReviewRating { get; set; }
    public string ReviewText { get; set; }

    public virtual Book Book { get; set; }
}
